import type { AppState, Quarter } from "./types";
import { QUARTERS } from "./types";

const now = () => new Date().toISOString();

const quarterThemes = QUARTERS.reduce((acc, quarter) => {
  acc[quarter] = {
    quarter,
    theme: "",
    goals: "",
  };
  return acc;
}, {} as Record<Quarter, AppState["quarterThemes"][Quarter]>);

export const sampleState: AppState = {
  meta: {
    year: 2026,
    productName: "Roadmap Planner",
    companyName: "Nordic Product Lab",
    updatedAt: now(),
  },
  northStar: {
    name: "Trusted partner for outcome-driven roadmaps",
    description:
      "Give leaders and teams a shared, outcome-first roadmap that adapts every quarter.",
    ahaDefinition: "Stakeholders reuse the roadmap without a kickoff meeting",
    primaryMetric: "Active roadmap shares per quarter",
  },
  metrics: [
    {
      id: "m1",
      name: "Activation rate",
      definition: "% of invited stakeholders viewing the roadmap",
      target: "+20%",
      owner: "PMM",
    },
    {
      id: "m2",
      name: "Time-to-alignment",
      definition: "Days from kickoff to approved roadmap",
      target: "-30%",
      owner: "CPM",
    },
    {
      id: "m3",
      name: "Delivery confidence",
      definition: "% of initiatives delivered within quarter",
      target: ">80%",
      owner: "Engineering",
    },
    {
      id: "m4",
      name: "Support load",
      definition: "Incoming roadmap clarification tickets",
      target: "<10/mo",
    },
  ],
  pillars: [
    { id: "p1", name: "Growth", icon: "rocket" },
    { id: "p2", name: "Retention", icon: "repeat" },
    { id: "p3", name: "Efficiency", icon: "gauge" },
    { id: "p4", name: "Trust", icon: "shield" },
    { id: "p5", name: "Platform", icon: "layers" },
  ],
  quarterThemes: {
    ...quarterThemes,
    Q1: {
      quarter: "Q1",
      theme: "Win stakeholder trust",
      goals: "Launch exec-ready roadmap view\nReduce handoff friction",
    },
    Q2: {
      quarter: "Q2",
      theme: "Scale execution",
      goals: "Improve delivery predictability\nPilot outcome reviews",
    },
    Q3: {
      quarter: "Q3",
      theme: "Deepen adoption",
      goals: "Expand to 3 business units",
    },
    Q4: {
      quarter: "Q4",
      theme: "Optimize portfolio",
      goals: "Focus on ROI-positive bets",
    },
  },
  initiatives: [
    {
      id: "i1",
      title: "Unified stakeholder dashboard",
      quarter: "Q1",
      pillarId: "p1",
      status: "committed",
      owner: "Lena",
      problem: "Stakeholders lack a single source of truth",
      outcome: "Execs self-serve roadmap updates",
      hypothesis: "If we publish a single dashboard, alignment meetings drop",
      scope: "Dashboard, filter summary, export",
      successMetrics: "Activation rate +20%",
      dependencies: "Data model finalization",
      risks: "Scope creep on analytics",
      confidence: "high",
      effort: "L",
      allocationPct: 30,
      tags: ["exec", "dashboard"],
      links: [{ label: "PRD", url: "https://example.com/prd" }],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "i2",
      title: "Quarterly theme generator",
      quarter: "Q1",
      pillarId: "p3",
      status: "likely",
      owner: "Morten",
      problem: "Teams spend time drafting themes",
      outcome: "Faster quarterly planning cycles",
      hypothesis: "Templates reduce planning time",
      scope: "Theme templates + prompts",
      successMetrics: "Time-to-alignment -30%",
      dependencies: "None",
      risks: "Low adoption",
      confidence: "medium",
      effort: "M",
      allocationPct: 15,
      tags: ["planning"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "i3",
      title: "Capacity guardrails",
      quarter: "Q2",
      pillarId: "p3",
      status: "committed",
      owner: "Sara",
      problem: "Over-committing teams",
      outcome: "Balanced capacity decisions",
      hypothesis: "Visual guardrails reduce over-allocation",
      scope: "Capacity widget + alerts",
      successMetrics: "Delivery confidence >80%",
      dependencies: "Allocation data",
      risks: "Teams ignore warnings",
      confidence: "high",
      effort: "M",
      allocationPct: 25,
      tags: ["capacity"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "i4",
      title: "Roadmap export pack",
      quarter: "Q2",
      pillarId: "p5",
      status: "likely",
      owner: "Jon",
      problem: "Sharing requires manual updates",
      outcome: "One-click sharing for leadership",
      hypothesis: "Export packs reduce support load",
      scope: "PDF + JSON export",
      successMetrics: "Support load <10/mo",
      dependencies: "Print stylesheet",
      risks: "Formatting issues",
      confidence: "medium",
      effort: "S",
      allocationPct: 10,
      tags: ["export"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "i5",
      title: "North star scorecard",
      quarter: "Q3",
      pillarId: "p2",
      status: "bet",
      owner: "Arne",
      problem: "Teams lose connection to outcomes",
      outcome: "Monthly outcome reviews",
      hypothesis: "Scorecards keep teams aligned",
      scope: "KPI dashboard + notes",
      successMetrics: "Activation rate +20%",
      dependencies: "Metric definitions",
      risks: "Stakeholder fatigue",
      confidence: "low",
      effort: "L",
      allocationPct: 20,
      tags: ["outcomes"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "i6",
      title: "Security review workflow",
      quarter: "Q4",
      pillarId: "p4",
      status: "committed",
      owner: "Maya",
      problem: "Compliance reviews are ad hoc",
      outcome: "Predictable trust reviews",
      hypothesis: "Standard workflow cuts review time",
      scope: "Checklist + evidence capture",
      successMetrics: "Time-to-alignment -30%",
      dependencies: "Legal input",
      risks: "Policy changes",
      confidence: "medium",
      effort: "M",
      allocationPct: 18,
      tags: ["trust"],
      createdAt: now(),
      updatedAt: now(),
    },
  ],
  capacityModel: {
    productValuePct: 70,
    platformPct: 20,
    discoveryOpsPct: 10,
  },
  filters: {
    search: "",
    quarters: ["Q1", "Q2", "Q3", "Q4"],
    statuses: ["committed", "likely", "bet"],
    pillars: [],
    owners: [],
    tags: [],
    showOnlyOverCapacity: false,
  },
  ui: {
    viewMode: "exec",
    sortMode: "default",
  },
};
